<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Bobs-MBP.fios-router.home" ignored="2" name="Test" tests="1" failures="1" timestamp="2020-06-23T00:50:48 EDT" time="16.371" errors="0">
  <testcase name="invalidUserName" time="8.462" classname="com.qa.tests.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.ffhdd]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.ffhdd]
at com.qa.tests.LoginTests.invalidUserName(LoginTests.java:70)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- invalidUserName -->
  <testcase name="succesfullLogin" time="0.0" classname="com.qa.tests.LoginTests">
    <ignored/>
  </testcase> <!-- succesfullLogin -->
  <testcase name="invalidPassword" time="0.0" classname="com.qa.tests.LoginTests">
    <ignored/>
  </testcase> <!-- invalidPassword -->
</testsuite> <!-- Test -->
